services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-webserver
    container_name: webserver-airflow
    depends_on:
      - postgres
    entrypoint: ["/opt/airflow/entrypoint.sh"]
    command: ["airflow", "webserver"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_UID=50000
      - AIRFLOW_GID=0
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__RBAC=True
      - PYTHONPATH=/opt/airflow
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-scheduler
    container_name: scheduler-airflow
    depends_on:
      - postgres
      - airflow-webserver
    command: ["airflow", "scheduler"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_UID=50000
      - AIRFLOW_GID=0
      - PYTHONPATH=/opt/airflow
    volumes:
      - .:/opt/airflow
volumes:
  postgres_data: